services:
  tapestry:
    container_name: tapestry
    build: .
    ports:
      - "8080:80"
      - "7777:7777"
      - "7778:7778"
      - "7474:7474"
      - "7687:7687"
      - "8687:8687"
    environment:
      - OWNER_PUBKEY=${OWNER_PUBKEY}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - DOMAIN_NAME=localhost
    volumes:
      - tapestry-neo4j:/var/lib/neo4j/data
      - tapestry-strfry:/var/lib/strfry
      - tapestry-data:/var/lib/brainstorm
      - tapestry-logs:/var/log/brainstorm
    restart: unless-stopped

volumes:
  tapestry-neo4j:
  tapestry-strfry:
  tapestry-data:
  tapestry-logs:
