import { useState, useMemo, useEffect } from 'react';
import { useOutletContext, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { createElement } from '../../api/normalize';
import { useCypher } from '../../hooks/useCypher';
import SchemaForm, { buildInitialValues, formValuesToJson } from '../../components/SchemaForm';

export default function NewElement() {
  const { concept, uuid } = useOutletContext();
  const navigate = useNavigate();
  const { user } = useAuth();
  const isOwner = user?.classification === 'owner';

  const [formValues, setFormValues] = useState({});
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);
  const [showPreview, setShowPreview] = useState(false);
  const [schemaInitialized, setSchemaInitialized] = useState(false);

  // Fetch schema
  const { data: schemaData, loading: schemaLoading } = useCypher(`
    MATCH (h:NostrEvent {uuid: '${uuid}'})
    OPTIONAL MATCH (js:JSONSchema)-[:IS_THE_JSON_SCHEMA_FOR]->(h)
    OPTIONAL MATCH (js)-[:HAS_TAG]->(jt:NostrEventTag {type: 'json'})
    OPTIONAL MATCH (h)-[:IS_THE_CONCEPT_FOR]->(sup:Superset)
    RETURN head(collect(jt.value)) AS schemaJson, sup.uuid AS supersetUuid
  `);

  const schema = useMemo(() => {
    const raw = schemaData?.[0]?.schemaJson;
    if (!raw) return null;
    try {
      const parsed = typeof raw === 'string' ? JSON.parse(raw) : raw;
      // Extract actual JSON Schema from word-wrapper format if present
      if (parsed.jsonSchema && typeof parsed.jsonSchema === 'object') {
        return parsed.jsonSchema;
      }
      return parsed;
    }
    catch { return null; }
  }, [schemaData]);

  const supersetUuid = schemaData?.[0]?.supersetUuid;

  // Initialize form values from schema defaults (once)
  useEffect(() => {
    if (schema && !schemaInitialized) {
      setFormValues(buildInitialValues(schema));
      setSchemaInitialized(true);
    }
  }, [schema, schemaInitialized]);

  // Derive element name from form values
  // Derive element name: check top-level fields first, then dig into the
  // primary property wrapper (e.g., formValues.tapestry.name)
  const elementName = useMemo(() => {
    // Top-level (no-schema fallback)
    if (formValues.name || formValues.title) return formValues.name || formValues.title;
    // Schema-driven: find the primary property key and look inside it
    if (schema?.properties) {
      const ppKey = Object.keys(schema.properties)[0];
      const pp = ppKey && formValues[ppKey];
      if (pp && typeof pp === 'object') {
        return pp.name || pp.slug || pp.title || '';
      }
    }
    return '';
  }, [formValues, schema]);

  // Build JSON from form values
  const jsonData = useMemo(() => {
    if (!schema) return formValues.name ? { name: formValues.name } : null;
    return formValuesToJson(schema, formValues);
  }, [schema, formValues]);

  // Build nostr event preview
  const previewEvent = useMemo(() => {
    const trimmed = (typeof elementName === 'string' ? elementName : '').trim();
    if (!trimmed) return null;

    const tags = [
      ['d', '<auto-generated>'],
      ['name', trimmed],
      ['z', supersetUuid || '<superset-uuid>'],
    ];
    if (jsonData) {
      tags.push(['json', JSON.stringify(jsonData)]);
    }

    return {
      kind: 39999,
      pubkey: '<tapestry-assistant>',
      created_at: '<now>',
      tags,
      content: '',
    };
  }, [elementName, supersetUuid, jsonData]);

  async function handleSubmit(e) {
    e.preventDefault();
    const trimmedName = (typeof elementName === 'string' ? elementName : '').trim();
    if (!trimmedName) return;
    setCreating(true);
    setError(null);
    setResult(null);
    try {
      const res = await createElement({
        concept: concept.name,
        name: trimmedName,
        json: jsonData,
      });
      setResult(res);
    } catch (err) {
      setError(err.message);
    } finally {
      setCreating(false);
    }
  }

  function handleReset() {
    setResult(null);
    setFormValues(schema ? buildInitialValues(schema) : {});
    setError(null);
    setShowPreview(false);
  }

  const hasProperties = schema?.properties && Object.keys(schema.properties).length > 0;

  return (
    <div>
      <h2>New Element</h2>
      <p style={{ opacity: 0.7 }}>
        Add a new element to the <strong>{concept?.name}</strong> concept.
      </p>

      {!isOwner && (
        <div className="health-banner health-warn" style={{ marginBottom: '1.5rem' }}>
          <span className="health-banner-icon">🔒</span>
          <span>Sign in as owner to create elements.</span>
        </div>
      )}

      {result ? (
        <div>
          <div className="health-banner health-pass" style={{ marginBottom: '1.5rem' }}>
            <span className="health-banner-icon">✅</span>
            <span className="health-banner-label">Element Created!</span>
          </div>

          <table className="data-table">
            <tbody>
              <tr><td><strong>Name</strong></td><td>{result.element.name}</td></tr>
              <tr><td><strong>UUID</strong></td><td><code className="uuid-short">{result.element.uuid}</code></td></tr>
              <tr><td><strong>Concept</strong></td><td>{result.element.concept}</td></tr>
            </tbody>
          </table>

          <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem' }}>
            <button
              className="btn"
              onClick={() => navigate(`/kg/databases/neo4j/nodes/${encodeURIComponent(result.element.uuid)}`)}
            >
              🔵 View Node
            </button>
            <button
              className="btn"
              onClick={() => navigate(`/kg/concepts/${encodeURIComponent(uuid)}/elements`)}
            >
              📋 Back to Elements
            </button>
            <button className="btn btn-primary" onClick={handleReset}>
              ➕ Add Another
            </button>
          </div>
        </div>
      ) : (
        <form onSubmit={handleSubmit} className="new-concept-form">
          {schemaLoading && <div className="loading">Loading schema…</div>}

          {!schemaLoading && hasProperties ? (
            <SchemaForm
              schema={schema}
              values={formValues}
              onChange={setFormValues}
              disabled={creating}
            />
          ) : !schemaLoading && (
            /* Fallback: no schema, just a name input */
            <div className="form-field">
              <label htmlFor="elem-name">Name <span className="required">*</span></label>
              <input
                id="elem-name"
                type="text"
                value={formValues.name || ''}
                onChange={e => setFormValues({ ...formValues, name: e.target.value })}
                placeholder={`e.g. a specific ${concept?.name || 'item'}`}
                required
                autoFocus
                disabled={creating}
              />
            </div>
          )}

          {error && (
            <div className="health-banner health-fail" style={{ marginTop: '1rem' }}>
              <span className="health-banner-icon">❌</span>
              <span>{error}</span>
            </div>
          )}

          <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem', alignItems: 'center' }}>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={!(typeof elementName === 'string' ? elementName : '').trim() || creating || !isOwner}
              title={!isOwner ? 'Sign in as owner to create elements' : ''}
            >
              {creating ? '⏳ Creating element…' : '➕ Add Element'}
            </button>
            {(typeof elementName === 'string' ? elementName : '').trim() && (
              <button
                type="button"
                className="btn"
                onClick={() => setShowPreview(p => !p)}
              >
                {showPreview ? '🔽 Hide Preview' : '▶️ Show Preview'}
              </button>
            )}
          </div>

          {showPreview && jsonData && (
            <div style={{ marginTop: '1.5rem' }}>
              <h3 style={{ fontSize: '1rem', marginBottom: '0.5rem' }}>📋 JSON Data Preview</h3>
              <pre className="json-block">{JSON.stringify(jsonData, null, 2)}</pre>

              <h3 style={{ fontSize: '1rem', marginTop: '1.5rem', marginBottom: '0.5rem' }}>📨 Nostr Event Preview</h3>
              <pre className="json-block">{JSON.stringify(previewEvent, null, 2)}</pre>
            </div>
          )}
        </form>
      )}
    </div>
  );
}
