import { useState, useMemo, useEffect } from 'react';
import { useOutletContext, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { createProperty } from '../../api/normalize';
import { useCypher } from '../../hooks/useCypher';

export default function NewProperty() {
  const { concept, uuid } = useOutletContext();
  const navigate = useNavigate();
  const { user } = useAuth();
  const isOwner = user?.classification === 'owner';

  const [creating, setCreating] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);
  const [showPreview, setShowPreview] = useState(false);

  // Form fields for a property (based on the BIOS "property" concept schema)
  const [propName, setPropName] = useState('');
  const [propType, setPropType] = useState('string');
  const [propDescription, setPropDescription] = useState('');
  const [propRequired, setPropRequired] = useState(false);
  const [propDefault, setPropDefault] = useState('');
  const [propFormat, setPropFormat] = useState('');
  const [propPattern, setPropPattern] = useState('');
  const [propEnum, setPropEnum] = useState('');
  const [parentUuid, setParentUuid] = useState(''); // set to primary property UUID on load

  const typeOptions = ['string', 'number', 'integer', 'boolean', 'object', 'array', 'null'];

  // Fetch the JSON Schema, Primary Property, and all object-typed properties as valid parent targets
  const { data: schemaRow } = useCypher(`
    MATCH (js:JSONSchema)-[:IS_THE_JSON_SCHEMA_FOR]->(h:NostrEvent {uuid: '${uuid}'})
    OPTIONAL MATCH (pp)-[:IS_THE_PRIMARY_PROPERTY_FOR]->(h)
    RETURN js.uuid AS schemaUuid, js.name AS schemaName,
           pp.uuid AS primaryUuid, pp.name AS primaryName
    LIMIT 1
  `);
  const { data: objectProps } = useCypher(`
    MATCH (js:JSONSchema)-[:IS_THE_JSON_SCHEMA_FOR]->(h:NostrEvent {uuid: '${uuid}'})
    OPTIONAL MATCH (pp)-[:IS_THE_PRIMARY_PROPERTY_FOR]->(h)
    WITH js, pp
    MATCH (p:Property)-[:IS_A_PROPERTY_OF*1..10]->(js)
    WHERE p <> pp
    OPTIONAL MATCH (p)-[:HAS_TAG]->(jt:NostrEventTag {type: 'json'})
    WITH p, head(collect(jt.value)) AS json
    RETURN p.uuid AS uuid, p.name AS name, json
  `);

  // Set default parent to primary property when data loads
  useEffect(() => {
    if (schemaRow?.length && schemaRow[0].primaryUuid && !parentUuid) {
      setParentUuid(schemaRow[0].primaryUuid);
    }
  }, [schemaRow]); // eslint-disable-line react-hooks/exhaustive-deps

  const parentChoices = useMemo(() => {
    if (!schemaRow?.length) return [];
    const { primaryUuid, primaryName } = schemaRow[0];
    // Default parent is the Primary Property (not the JSON Schema)
    const defaultLabel = primaryName || 'Primary Property (top level)';
    const defaultUuid = primaryUuid || '';
    const choices = [{ uuid: defaultUuid, label: defaultLabel, isDefault: true }];
    if (Array.isArray(objectProps)) {
      for (const p of objectProps) {
        if (!p.uuid) continue;
        let pType = null;
        try {
          const parsed = typeof p.json === 'string' ? JSON.parse(p.json) : p.json;
          pType = parsed?.property?.type;
        } catch {}
        if (pType === 'object') {
          choices.push({ uuid: p.uuid, label: `↳ ${p.name} (object)`, isDefault: false });
        }
      }
    }
    return choices;
  }, [schemaRow, objectProps]);

  const schemaUuid = schemaRow?.[0]?.schemaUuid;

  // Build the property JSON preview
  const previewJson = useMemo(() => {
    const trimmed = propName.trim();
    if (!trimmed) return null;

    const obj = { name: trimmed, type: propType };
    if (propDescription.trim()) obj.description = propDescription.trim();
    obj.required = propRequired;
    if (propDefault.trim()) {
      // Try to parse as JSON, fall back to string
      try { obj.default = JSON.parse(propDefault.trim()); }
      catch { obj.default = propDefault.trim(); }
    }
    if (propFormat.trim()) obj.format = propFormat.trim();
    if (propPattern.trim()) obj.pattern = propPattern.trim();
    if (propEnum.trim()) {
      try { obj.enum = JSON.parse(propEnum.trim()); }
      catch { /* ignore invalid JSON */ }
    }

    return { property: obj };
  }, [propName, propType, propDescription, propRequired, propDefault, propFormat, propPattern, propEnum]);

  // Build the nostr event preview
  const previewEvent = useMemo(() => {
    const trimmed = propName.trim();
    if (!trimmed) return null;
    const tags = [
      ['d', '<auto-generated>'],
      ['name', trimmed],
      ['description', propDescription.trim()],
      ['type', propType],
      ['z', '<bios-property-header-uuid>'],
    ];
    if (previewJson) tags.push(['json', JSON.stringify(previewJson)]);
    return { kind: 39999, pubkey: '<tapestry-assistant>', created_at: '<now>', tags, content: '' };
  }, [propName, propType, propDescription, previewJson]);

  async function handleSubmit(e) {
    e.preventDefault();
    if (!propName.trim()) return;
    setCreating(true);
    setError(null);
    setResult(null);
    try {
      const opts = {
        name: propName.trim(),
        type: propType,
        description: propDescription.trim(),
        required: propRequired,
      };
      if (parentUuid) {
        opts.parentUuid = parentUuid;
      } else {
        // Fallback: use concept name if no parent UUID (shouldn't happen with primary property)
        opts.concept = concept.name;
      }
      const res = await createProperty(opts);
      setResult(res);
    } catch (err) {
      setError(err.message);
    } finally {
      setCreating(false);
    }
  }

  function handleReset() {
    setResult(null);
    setPropName('');
    setPropType('string');
    setPropDescription('');
    setPropRequired(false);
    setPropDefault('');
    setPropFormat('');
    setPropPattern('');
    setPropEnum('');
    setParentUuid('');
    setError(null);
    setShowPreview(false);
  }

  return (
    <div>
      <h2>New Property</h2>
      <p style={{ opacity: 0.7 }}>
        Add a new property to the <strong>{concept?.name}</strong> concept's JSON Schema.
      </p>

      {!isOwner && (
        <div className="health-banner health-warn" style={{ marginBottom: '1.5rem' }}>
          <span className="health-banner-icon">🔒</span>
          <span>Sign in as owner to create properties.</span>
        </div>
      )}

      {result ? (
        <div>
          <div className="health-banner health-pass" style={{ marginBottom: '1.5rem' }}>
            <span className="health-banner-icon">✅</span>
            <span className="health-banner-label">Property Created!</span>
          </div>

          <table className="data-table">
            <tbody>
              <tr><td><strong>Name</strong></td><td>{result.property.name}</td></tr>
              <tr><td><strong>Type</strong></td><td>{result.property.type}</td></tr>
              <tr><td><strong>UUID</strong></td><td><code className="uuid-short">{result.property.uuid}</code></td></tr>
              <tr><td><strong>Target</strong></td><td>{result.property.targetName}</td></tr>
            </tbody>
          </table>

          <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem' }}>
            <button className="btn" onClick={() => navigate(`/kg/databases/neo4j/nodes/${encodeURIComponent(result.property.uuid)}`)}>
              🔵 View Node
            </button>
            <button className="btn" onClick={() => navigate(`/kg/concepts/${encodeURIComponent(uuid)}/properties`)}>
              📋 Back to Properties
            </button>
            <button className="btn btn-primary" onClick={handleReset}>
              ➕ Add Another
            </button>
          </div>
        </div>
      ) : (
        <form onSubmit={handleSubmit} className="new-concept-form">
          <div className="form-field">
            <label htmlFor="prop-name">Name <span className="required">*</span></label>
            <input
              id="prop-name"
              type="text"
              value={propName}
              onChange={e => setPropName(e.target.value)}
              placeholder="e.g. color, age, address"
              required
              autoFocus
              disabled={creating}
            />
          </div>

          {parentChoices.length > 1 && (
            <div className="form-field">
              <label htmlFor="prop-parent">Parent</label>
              <select
                id="prop-parent"
                value={parentUuid}
                onChange={e => setParentUuid(e.target.value)}
                disabled={creating}
              >
                {parentChoices.map(c => (
                  <option key={c.uuid} value={c.uuid}>{c.label}</option>
                ))}
              </select>
              <small style={{ opacity: 0.6 }}>
                Top-level properties attach to the JSON Schema. Nested properties attach to an object-typed property.
              </small>
            </div>
          )}

          <div className="form-field">
            <label htmlFor="prop-type">Type <span className="required">*</span></label>
            <select
              id="prop-type"
              value={propType}
              onChange={e => setPropType(e.target.value)}
              disabled={creating}
            >
              {typeOptions.map(t => <option key={t} value={t}>{t}</option>)}
            </select>
          </div>

          <div className="form-field">
            <label htmlFor="prop-description">Description</label>
            <textarea
              id="prop-description"
              value={propDescription}
              onChange={e => setPropDescription(e.target.value)}
              placeholder="A human-readable description of what this property represents"
              rows={2}
              disabled={creating}
            />
          </div>

          <div className="form-field" style={{ flexDirection: 'row', alignItems: 'center', gap: '0.5rem' }}>
            <input
              id="prop-required"
              type="checkbox"
              checked={propRequired}
              onChange={e => setPropRequired(e.target.checked)}
              disabled={creating}
            />
            <label htmlFor="prop-required" style={{ margin: 0 }}>Required</label>
          </div>

          <details style={{ marginTop: '1rem' }}>
            <summary style={{ cursor: 'pointer', opacity: 0.7 }}>Advanced Options</summary>
            <div style={{ marginTop: '0.75rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div className="form-field">
                <label htmlFor="prop-default">Default Value</label>
                <input
                  id="prop-default"
                  type="text"
                  value={propDefault}
                  onChange={e => setPropDefault(e.target.value)}
                  placeholder="JSON value (e.g. &quot;red&quot;, 0, true)"
                  disabled={creating}
                />
              </div>

              <div className="form-field">
                <label htmlFor="prop-format">Format</label>
                <input
                  id="prop-format"
                  type="text"
                  value={propFormat}
                  onChange={e => setPropFormat(e.target.value)}
                  placeholder="e.g. date-time, uri, email, uuid"
                  disabled={creating}
                />
              </div>

              <div className="form-field">
                <label htmlFor="prop-pattern">Pattern</label>
                <input
                  id="prop-pattern"
                  type="text"
                  value={propPattern}
                  onChange={e => setPropPattern(e.target.value)}
                  placeholder="Regular expression (e.g. ^[a-z]+$)"
                  disabled={creating}
                />
              </div>

              <div className="form-field">
                <label htmlFor="prop-enum">Enum Values</label>
                <input
                  id="prop-enum"
                  type="text"
                  value={propEnum}
                  onChange={e => setPropEnum(e.target.value)}
                  placeholder='JSON array (e.g. ["red", "blue", "green"])'
                  disabled={creating}
                />
              </div>
            </div>
          </details>

          {error && (
            <div className="health-banner health-fail" style={{ marginTop: '1rem' }}>
              <span className="health-banner-icon">❌</span>
              <span>{error}</span>
            </div>
          )}

          <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem', alignItems: 'center' }}>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={!propName.trim() || creating || !isOwner}
              title={!isOwner ? 'Sign in as owner to create properties' : ''}
            >
              {creating ? '⏳ Creating property…' : '➕ Add Property'}
            </button>
            {propName.trim() && (
              <button type="button" className="btn" onClick={() => setShowPreview(p => !p)}>
                {showPreview ? '🔽 Hide Preview' : '▶️ Show Preview'}
              </button>
            )}
          </div>

          {showPreview && previewJson && (
            <div style={{ marginTop: '1.5rem' }}>
              <h3 style={{ fontSize: '1rem', marginBottom: '0.5rem' }}>📋 Property JSON Preview</h3>
              <pre className="json-block">{JSON.stringify(previewJson, null, 2)}</pre>

              <h3 style={{ fontSize: '1rem', marginTop: '1.5rem', marginBottom: '0.5rem' }}>📨 Nostr Event Preview</h3>
              <pre className="json-block">{JSON.stringify(previewEvent, null, 2)}</pre>
            </div>
          )}
        </form>
      )}
    </div>
  );
}
